[package]
name = "rand-task"
version = "0.3.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
dotenv = "0.15.0"
rand = "0.8.5"
reqwest = "0.11.12"
rtctl = { path = "../rtctl" }
tokio = { version = "1", features = ["full"] }
wait-timeout = "0.2.0"
