//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub mod records;
pub mod tasks;

pub use records::Entity as Records;
pub use records::Model as Record;
pub use tasks::Entity as Tasks;
pub use tasks::Model as Task;
